name: Enrollware Data Export

on:
  schedule:
    # 每天凌晨2点运行
    - cron: '0 2 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        echo "Dependencies installed successfully"
        
    - name: Setup Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "Chrome installed at: $(which chromium-browser)"
        
    - name: Create downloads directory
      run: |
        mkdir -p downloads
        echo "Downloads directory created"
    - name: Create chrome-data directory
      run: |
        mkdir -p chrome-data
        echo "chrome-data directory created"
        
    - name: List files
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        echo "Downloads directory:"
        ls -la downloads/ || echo "Directory not found"
        
    - name: Run export script
      env:
        EW_USER: ${{ secrets.EW_USER }}
        EW_PASS: ${{ secrets.EW_PASS }}
        CHROME_BIN: /usr/bin/chromium-browser
        NODE_ENV: production
      run: |
        echo "Starting export script..."
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        node login_and_export.js
        
    - name: List downloaded files
      run: |
        echo "Checking downloaded files..."
        ls -la downloads/ || echo "Downloads directory not found"
        
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: enrollware-exports
        path: downloads/
        retention-days: 7
        
    - name: Send success notification
      if: success()
      run: |
        echo "✅ Enrollware export completed successfully!"
        echo "📁 Files saved as GitHub Actions artifacts"
        echo "📥 You can download files from the Actions page"
        
    - name: Send failure notification
      if: failure()
      run: |
        echo "❌ Enrollware export failed!"
        echo "Please check the logs for details" 