name: Enrollware Data Export

on:
  schedule:
    # 每天凌晨2点运行
    - cron: '0 2 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        
    - name: Create downloads directory
      run: mkdir -p enrollware-bot/downloads
      
    - name: Run export script
      env:
        EW_USER: ${{ secrets.EW_USER }}
        EW_PASS: ${{ secrets.EW_PASS }}
        CHROME_BIN: /usr/bin/chromium-browser
      run: |
        cd enrollware-bot
        node login_and_export.js
        
    - name: List downloaded files
      run: ls -la enrollware-bot/downloads/
      
    - name: Upload to Google Drive
      if: success()
      uses: burnett01/upload-google-drive@v1.0.0
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        local_file_path: './enrollware-bot/downloads/'
        drive_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        
    - name: Send success notification
      if: success()
      run: |
        echo "✅ Enrollware export completed successfully!"
        echo "📁 Files uploaded to Google Drive"
        
    - name: Send failure notification
      if: failure()
      run: |
        echo "❌ Enrollware export failed!"
        echo "Please check the logs for details" 